local M = {}

function M.get()
	return {
		-- colors
		OctoGrey = { fg = C.base, ctermfg = T.base },
		OctoBlue = { fg = C.blue, ctermfg = T.blue },
		OctoGreen = { fg = C.green, ctermfg = T.green },
		OctoRed = { fg = C.red, ctermfg = T.red },
		OctoPurple = { fg = C.mauve, ctermfg = T.mauve },
		OctoYelow = { fg = C.yellow, ctermfg = T.yellow },
		-- highlight groups
		OctoDirty = { link = "ErrorMsg" },
		OctoIssueTitle = { link = "PreProc" },
		OctoIssueId = { link = "Question" },
		OctoEmpty = { link = "Comment" },
		OctoFloat = { link = "NormalNC" },
		OctoDate = { link = "Comment" },
		OctoSymbol = { link = "Comment" },
		OctoTimelineItemHeading = { link = "Comment" },
		OctoDetailsLabel = { link = "Title" },
		OctoMissingDetails = { link = "Comment" },
		OctoDetailsValue = { link = "Identifier" },
		OctoDiffHunkPosition = { link = "NormalFloat" },
		OctoCommentLine = { link = "TabLineSel" },
		OctoEditable = { fg = C.text, ctermfg = T.text, bg = C.mantle, ctermbg = T.mantle },
		OctoViewer = { fg = C.base, ctermfg = T.base, bg = C.blue, ctermbg = T.blue },
		OctoBubble = { fg = C.text, ctermfg = T.text, bg = C.mantle, ctermbg = T.mantle },
		OctoBubbleGrey = { fg = C.text, ctermfg = T.text, bg = C.mantle, ctermbg = T.mantle },
		OctoBubbleDelimiterGrey = { fg = C.mantle, ctermfg = T.mantle },
		OctoBubbleGreen = { fg = C.base, ctermfg = T.base, bg = C.green, ctermbg = T.green },
		OctoBubbleDelimiterGreen = { fg = C.green, ctermfg = T.green },
		OctoBubbleBlue = { fg = C.base, ctermfg = T.base, bg = C.sky, ctermbg = T.sky },
		OctoBubbleDelimiterBlue = { fg = C.sky, ctermfg = T.sky },
		OctoBubbleYellow = { fg = C.base, ctermfg = T.base, bg = C.yellow, ctermbg = T.yellow },
		OctoBubbleDelimiterYellow = { fg = C.yellow, ctermfg = T.yellow },
		OctoBubbleRed = { fg = C.base, ctermfg = T.base, bg = C.red, ctermbg = T.red },
		OctoBubbleDelimiterRed = { fg = C.red, ctermfg = T.red },
		OctoBubblePurple = { fg = C.base, ctermfg = T.base, bg = C.mauve, ctermbg = T.mauve },
		OctoBubbleDelimiterPurple = { fg = C.mauve, ctermfg = T.mauve },
		OctoUser = { link = "OctoBubble" },
		OctoUserViewer = { link = "OctoViewer" },
		OctoReaction = { link = "OctoBubble" },
		OctoReactionViewer = { link = "OctoViewer" },
		OctoPassingTest = { link = "OctoGreen" },
		OctoFailingTest = { link = "OctoRed" },
		OctoPullAdditions = { link = "OctoGreen" },
		OctoPullDeletions = { link = "OctoRed" },
		OctoPullModifications = { fg = C.peach, ctermfg = T.peach },
		OctoStateOpen = { fg = C.green, ctermfg = T.green, bg = C.mantle, ctermbg = T.mantle },
		OctoStateOpenFloat = { fg = C.green, ctermfg = T.green, bg = C.mantle, ctermbg = T.mantle },
		OctoStateClosed = { fg = C.red, ctermfg = T.red, bg = C.mantle, ctermbg = T.mantle },
		OctoStateClosedFloat = { fg = C.red, ctermfg = T.red, bg = C.mantle, ctermbg = T.mantle },
		OctoStateMerged = { fg = C.mauve, ctermfg = T.mauve, bg = C.mantle, ctermbg = T.mantle },
		OctoStateMergedFloat = { fg = C.mauve, ctermfg = T.mauve, bg = C.mantle, ctermbg = T.mantle },
		OctoStatePending = { fg = C.peach, ctermfg = T.peach, bg = C.mantle, ctermbg = T.mantle },
		OctoStatePendingFloat = { fg = C.peach, ctermfg = T.peach, bg = C.mantle, ctermbg = T.mantle },
		OctoStateApproved = { link = "OctoStateOpen" },
		OctoStateApprovedFloat = { link = "OctoStateOpen" },
		OctoStateChangesRequested = { fg = C.marron, ctermfg = T.marron, bg = C.mantle, ctermbg = T.mantle },
		OctoStateChangesRequestedFloat = { fg = C.marron, ctermfg = T.marron, bg = C.mantle, ctermbg = T.mantle },
		OctoStateCommented = { link = "Normal" },
		OctoStateCommentedFloat = { link = "Normal" },
		OctoStateDismissed = { link = "OctoStateClosed" },
		OctoStateDismissedFloat = { link = "OctoStateClosed" },
		OctoStateSubmittedBubble = { link = "OctoBubbleGreen" },
		OctoFilePanelCounter = { fg = C.blue, ctermfg = T.blue, style = { "bold" } },
		OctoFilePanelTitle = { fg = C.blue, ctermfg = T.blue, style = { "bold" } },
		OctoNormalFront = { fg = C.text, ctermfg = T.text },
		OctoYellowFloat = { fg = C.yellow, ctermfg = T.yellow, bg = C.mantle, ctermbg = T.mantle },
		OctoPurpleFloat = { fg = C.mauve, ctermfg = T.mauve, bg = C.mantle, ctermbg = T.mantle },
		OctoRedFloat = { fg = C.red, ctermfg = T.red, bg = C.mantle, ctermbg = T.mantle },
		OctoGreenFloat = { fg = C.green, ctermfg = T.green, bg = C.mantle, ctermbg = T.mantle },
		OctoGreyFloat = { fg = C.text, ctermfg = T.text, bg = C.mantle, ctermbg = T.mantle },
		OctoBlueFloat = { fg = C.blue, ctermfg = T.blue, bg = C.mantle, ctermbg = T.mantle },
	}
end

return M
